### ISSUE TITLE
Enconding problems

### ISSUE THREAD

**Issue by leandrocodes** [yoobi55/ionic-trivia#1]
Hey, i can't find a solution for the enconding problem.

Some issues:
"&Quot"
"&#349"
"&#039"

**Comment by biyootiful** [comment]
Since I'm not the author of the API, you could write a helper function after fetching the response. For instance,

```
function htmlDecode( input ) {
    return String(input)
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>');
        ... you get the idea
} 
```
Or since the issue is about HTML entities, you could investigate a way to directly place the response in HTML. Hope this helps!

**Comment by biyootiful** [comment]
I'm closing the issue. Please let me know if you have any other issues.

**Comment by action7777** [comment]
Just change `<h2 class="question">{{currentQuiz.question}}</h2>`
with this:
`<h2 class="question" [innerHTML]="currentQuiz.question"></h2>`
